# This is a basic workflow to help you get started with Actions

name: baseCode

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_pull_request:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Create PR
       run: |
        git checkout -b feature/TSbranch
        
        echo "New feature code" >> feature-file.txt
        
        git add .
        git commit -m "Update files"
        git push origin feature/TSbranch
        gh pr create --title "Pull Request from Linux to Windows" --body "This is a pull request created by GitHub Actions" --base main --head feature/TSbranch
