# This is a basic workflow to help you get started with Actions

name: baseCode

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_pull_request:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '14'

     - name: Install dependencies
       run: npm install

     - name: Create new branch
       run: git switch -b feature/Testbranch

     - name: Make changes
       run: echo "New feature code" >> feature-file.txt

     - name: Commit changes
       run: |
         git config --local user.email "thebluesky93@naver.com"
         git config --local user.name "Skyler Hwang"
         git add .
         git commit -m "Add new feature"

     - name: Push changes to new branch
       run: git push origin feature/Testbranch

     - name: Create Pull Request
       uses: actions/github-script@v4
       with:
         github-token: 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 
         script: |
           const { data: pr } = await github.pulls.create({
             owner: 'poohSky',
             repo: 'dispatch_From',
             title: 'New feature Pull Request',
             head: 'feature/Testbranch',
             base: 'main'
           });
           console.log(`Created Pull Request: ${pr.html_url}`);
