# This is a basic workflow to help you get started with Actions

name: From Workflow

on:
 repository_dispatch:
   types:
     - trigger-workflow

jobs:
 from:
   runs-on: self-hosted

   steps:
     - name: Checkout test
       uses: actions/checkout@v2
       
     - name: echo hello
       run: echo hello Test
