# This is a basic workflow to help you get started with Actions

name: BuildTest

on:
 push:
    branches: [ "main" ]

jobs:
 from:
   runs-on: [ "self-hosted" ]

   steps:
     - name: Checkout Repo
       uses: actions/checkout@v2
       
     - name: echo hello
       run: echo "hello Test"
