# This is a basic workflow to help you get started with Actions

name: createPR_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_pull_request:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    steps:
     - name: Checkout code
       uses: actions/checkout@v3
       #with:
       #  token: ${{ secrets.G_ACCESS_TOKEN }}
       #  submodules: true

     - name: check git branch
       run: |
         ls
         Remove-Item -Path ".\dispatch_From\*" -Force -Recurse
         git submodule update --init --recursive
         
         git status
         git branch
         git submodule update --remote

     - name: Set up Git
       run: |
         git config --global user.email "thebluesky93@naver.com"
         git config --global user.name "poohSky"
        
     - name: Create TSbranch in submodule
       run: |
         cd dispatch_From

         git branch -D feature/TSbranch
         git checkout -b feature/TSbranch
         
         echo "This is a test file." > test.txt
         git add test.txt
         
         echo "git status"
         git status
         
         git commit -m "Add test.txt"
         echo "push origin feature/TSbranch"
         git push origin feature/TSbranch
       env:
         GITHUB_TOKEN: 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

     - name: Create Pull Request
       run: |
         cd dispatch_From

         gh pr create --base main --head feature/TSbranch --title "create PR test" --body "Test body :earth_asia:"
          
 #       curl -X POST -H "Authorization: token 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" -d '{
 #       "title": "Test Pull Request Title",
 #       "body": "Pull Request Body :earth_asia:",
 #       "head": "feature/PSbranch",
 #       "base": "main"
 #       }' https://api.github.com/repos/poohSky/dispatch_To/pulls
