# This is a basic workflow to help you get started with Actions

name: createPR_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_pull_request:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
      
    steps:
     - name: Checkout action
       uses: actions/checkout@v3
          
     - name: Checkout submodule
       uses: actions/checkout@v3
       with:
         repository: poohSky/dispatch_From
         path: dispatch_From
        
     - name: Update submodule and create branch
       run: |
        cd dispatch_From

         git branch -D feature/TSbranch
         git checkout -b feature/TSbranch
        echo "test git status check point"
        git status

        git config --global credential.helper store
        git config --local user.name "poohSky"
        git config --local user.email "thebluesky93@naver.com"

        echo "This is a test file." > test.txt
        git add .
        git commit -m "Add test.txt"

        echo "test check point"
        git status
        git branch

        echo "git push check"
        git push --force origin feature/TSbranch
       env:
         token: ${{ secrets.GITHUB_TOKEN }} 
         
     - name: Create Pull Request
       run: |
         # Set the repository and branch information
         REPO_OWNER=poohSky
         REPO_NAME=dispatch_From
         BASE_BRANCH=main
         HEAD_BRANCH=TestBranch

         # Create Pull Request from the submodule repository
         gh pr create --base $BASE_BRANCH --head $REPO_OWNER:$HEAD_BRANCH --title "Create PR test" --body "Test body :earth_asia:" --repo $REPO_OWNER/$REPO_NAME
         
 # start --------------------------------------------------------------------------------------------------------------------
 #    - name: Get GitHub User and Email
 #      run: |
 #       GITHUB_USER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user | Select-Object -ExpandProperty login)
 #       GITHUB_EMAIL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user | Select-Object -ExpandProperty email)

 #    - name: Create Pull Request
 #      run: |
 #       GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
 #       GITHUB_REPOSITORY=${{ github.repository }}
 #       REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d / -f 1)
 #       REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d / -f 2)
 #       TITLE="create PR test"
 #       BODY="Test body :earth_asia:"
        
 #       gh pr create --base main --head $GITHUB_USER:feature/TSbranch --title "$TITLE" --body "$BODY" --repo $REPO_OWNER/$REPO_NAME
 # end --------------------------------------------------------------------------------------------------------------------
 
 #       curl -X POST -H "Authorization: token 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" -d '{
 #       "title": "Test Pull Request Title",
 #       "body": "Pull Request Body :earth_asia:",
 #       "head": "feature/PSbranch",
 #       "base": "main"
 #       }' https://api.github.com/repos/poohSky/dispatch_To/pulls
